### ISSUE TITLE
Offset between groundtruth crops and raw data?

### ISSUE THREAD

**Issue by giomalt** [janelia-cosem/heinrich-2021a#1]
Dear Janelia devs,

first of all thanks for the effort you put in this work and in making it accessible to everyone!

I'd like to play with some of your datasets, such as the raw data and manual groundtruth, but I'm a bit confused about their relative positioning and units.

For example, in the case of hela-2, raw data and crop1, we read from their metadata:

[raw data](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/jrc_hela-2/jrc_hela-2.n5/volumes/raw/s0/attributes.json)
[groundtrtuh, crop1](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/jrc_hela-2/jrc_hela-2.n5/volumes/groundtruth/0003/Crop1/labels/all/attributes.json)

that:

- raw data has a shape (`dimensions`) of `[12000, 1600, 6368]` voxels (I think in voxels unit), and no offset (`translate`=0)
- crop 1 has an `offset` of `[25864, 900, 2400]` nm, which given the resolution of 2 nm/voxel, should correspond to `[12932, 450, 1200]` voxels

Thus my 2 questions:
1. Is there an offset between the raw data and the crops, since the crop offset is bigger than all the dimensions of the raw dataset?
2. Are the crops data ordered as (z,y,x), as the raw data?

Thanks for your feedback,
Giorgio

**Comment by neptunes5thmoon** [comment]
Hi Giorgio,

thanks for bringing this up - I think it is a common source of confusion.

To answer your first question:
The annotations are at double the resolution of the raw data, specifically the raw data is 4nm/voxel, annotations are at 2 nm/voxel. The `offset` attribute is given in nm (as indicated by `offset_unit`) while the `dimensions` (as a core n5 attribute) are always in voxel units. That means that when you compare the `offset` attribute you read from the crop to the `dimensions` of the raw data as you tried to do here, you have to divide the offset by the raw data resolution, i.e. 4nm/voxel -> (6466, 225, 600)

Regarding your second question:
n5 itself generally works in "(x,y,z) order". So unless explicitly stated otherwise attributes like `offset` and `resolution` will be in that order. Note that when you use zarr to read n5 files this will switch the order to "(z,y,x)" because that's what python likes. But for the attributes you will have to do this yourself.
So as an example:
```
>>> from fibsem_tools.io import read
>>> x = read('s3://janelia-cosem-publications/heinrich-2021a/jrc_hela-2/jrc_hela-2.n5/volumes/groundtruth/0003/Crop1/labels/all', storage_options={'normalize_keys': False, "anon":True})
>>> print(x.shape) #zyx
(200, 1000, 1000)
>>> print(x.attrs["offset"]) #xyz
[25864.0, 900.0, 2400.0]
```
We recently started introducing the `transform` attributes as in `volumes/raw/s0` which is more explicit about the axes.

Hope this helps!

**Comment by neptunes5thmoon** [comment]
I'm gonna close this issue. Feel free to reopen it if you still have problems.

**Comment by giomalt** [comment]
Thanks for the clear answer Larissa. 
I'd like to add the recipe that worked for me, as I realised that the crop blocks, with respect to the raw data from `janelia-cosem`, are flipped along y.

1) download the [raw data](https://open.quiltdata.com/b/janelia-cosem/tree/jrc_hela-2/jrc_hela-2.n5/em/fibsem-uint8/s0/)(`4nm/voxel`)

2) download the [ground-truth](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/jrc_hela-2/jrc_hela-2.n5/volumes/groundtruth/0003/)(`2nm/voxel)`


For a single gt block:

3) downsample it from `2nm/voxel` to `4nm/voxel` (`[::2, ::2, ::2]`)

4) flip it along the y axis (`[,::-1,]`)

4) From the crop metadata, you can read its:
- offset `[x_gt, y_gt, z_gt]`
- shape `[dx_gt, dy_gt, dz_gt] `

and from the raw dataset metadata, the raw dataset shape:
- shape `[dx_raw, dy_raw, dz_raw] `

You can now position the gt crop on the raw dataset by using the following coordinates mapping:

```
x_gt -> x_gt * 0.25
y_gt -> dy_raw -  0.5* dy_gt - 0.25* y_gt
z_gt -> z_gt * 0.25
```
note: it seems to me that in the dataset 'jurkat' you need to add an additional `-10px` offset along `y_gt`:
`y_gt -> dy_raw -  0.5* dy_gt - 0.25* y_gt  - 10
`

Hope this helps anyone who needs to perform the same operation in the future :)

**Comment by d-v-b** [comment]
@giomalt sorry for the trouble here. The fact that some datasets are flipped along the y axis over in `janelia-cosem` is basically an early mistake that I made, and I have not yet gotten around to fixing it. Sorry for any inconvenience this has caused you. I'm working on fixing it, but it might take some time.

**Comment by neptunes5thmoon** [comment]
One thing to be aware of is that we use 2nm/voxel annotations as a compromise to efficiently encode semantic segmentation alongside instance segmentation information, i.e. at 2nm/voxel we were able to guarantee that several instances of the same object class do not touch. If you just downsample to 4nm objects can be "merged".

**Comment by giomalt** [comment]
@d-v-b no worries!
@neptunes5thmoon thanks for the clarification. We're doing semantic segmentation, so we do not worry if different instances are merged. Nice to know it in any case!
