### ISSUE TITLE
groundtruth data

### ISSUE THREAD

**Issue by bookuil** [janelia-cosem/heinrich-2021a#4]
Hi, thanks for your effort putting in this work!
I'm a bit confused about your groundtruth data. Here are my questions.

1. the relationship between dimensions and offset of groundtruth crops.
For example, in crop1, jrc_hela-2, [crop1](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/jrc_hela-2/jrc_hela-2.n5/volumes/groundtruth/0003/crop1/labels/all/attributes.json) the dimensions are **[1000,1000,200]** (I think it means it has a shape of [1000,1000,200] voxels). But, since it has an offset of **[25864, 900, 2400]** nm and given its 2nm/voxel resolution, I'm not clear how its dimensions were computed.

2. I only found the manually annotated data in groundtruth file. I wonder where I can find the raw data to match the annotated crops.

Thanks for your feedback,
bookuil

**Comment by neptunes5thmoon** [comment]
Hi,
sorry about missing this. I'll repeat here what I wrote in my email:

You'll find the annotations in each of the 5 datasets `jrc_hela-2`, `jrc_hela-3`, `jrc_jurkat-1`, `jrc_macrophage-2`, `jrc_sum159-1` under `volumes/groundtruth/0003/crop<cropno>`. 

Most classes will be in one array (`labels/all`) where each class will have its own unique id (see [README](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/README.md) ) but some classes have a dedicated array because they are not mutually exclusive with all other classes. As for the alignment with the raw data (which you'll find in `volumes/raw` as a multiscale pyramid for each dataset) you should refer to the `offset` in the meta data for each crop (e.g. [attributes for crop87](https://open.quiltdata.com/b/janelia-cosem-publications/tree/heinrich-2021a/jrc_hela-3/jrc_hela-3.n5/volumes/groundtruth/0003/crop87/labels/all/attributes.json))

The discussion in this issue might help too: #1 

Best,
Larissa

**Comment by bookuil** [comment]
Thanks Larissa, that's really helpful.

**Comment by neptunes5thmoon** [comment]
closing this for now, let us know if you run into more issues

**Comment by bookuil** [comment]
Hi,
There are two more issues I'm currently struggling with.
1) Since the ground truth is `2nm/voxel` and the raw data is `4nm/voxel`, I'm wondering which downsample method you used to generate the training label. Currently I'm  using the simple `[::2,::2,::2]`.
2) I noticed that the shape of your crops vary, I'm wondering what your network input size is. I've read the [training_setups](https://github.com/janelia-cellmap/training_setups), but got a little confused.

Thanks for your feedback.

**Comment by neptunes5thmoon** [comment]
Hi,

1. I calculated the distance transform at 2nm/voxel and then downsampled with [::2,::2,::2].
2. It depends a little bit, but typically I would use something like input (216,216,216) output (36,36,36) for training

Hope that helps
Larissa

**Comment by bookuil** [comment]
Thanks for your reply!
